name: web_scraping
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.12.0-259.12.beta <3.0.0'

dependencies:
  beautiful_soup_dart: ^0.3.0
  flutter:
    sdk: flutter
  http: ^0.13.6
  web_scraper: ^0.1.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
